apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins-ingress
  namespace: rt
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    acme.cert-manager.io/http01-edit-in-place: "true"  
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - jenkins.yplank.fr
    secretName: jenkins-tls-secret
  rules:
  - host: jenkins.yplank.fr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jenkins-svc
            port:
              number: 80