---
# Version de Calico à déployer
calico_version: v3.27.0

# URL du manifest Calico "tout-en-un"
calico_manifest_url: "https://raw.githubusercontent.com/projectcalico/calico/{{ calico_version }}/manifests/calico.yaml"

# Namespace attendu pour les pods Calico (manifests récents -> calico-system)
calico_namespace: calico-system

# Temps d'attente max (en secondes) pour que les pods Calico soient Ready
calico_wait_timeout: 300
