---
# Kubernetes version
k8s_prereqs_k8s_repo_version: v1.34

k8s_prereqs_containerd_config_dir: /etc/containerd
k8s_prereqs_containerd_config: /etc/containerd/config.toml

k8s_prereqs_sysctl_file: /etc/sysctl.conf
k8s_prereqs_sysctl_ip_forward: "1"

k8s_prereqs_modules_conf: /etc/modules-load.d/k8s.conf
k8s_prereqs_modules:
  - overlay
  - br_netfilter

