{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "dockerhub-auth-secret",
    "namespace": "rt"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "dockerhub-auth-secret",
        "namespace": "rt"
      },
      "type": "kubernetes.io/dockerconfigjson"
    },
    "encryptedData": {
      ".dockerconfigjson": "AgCPuwkzplU89VoD0qbibj/oQit74aZdQNYlaSIFmz4DerIE5iTTsNR9W+REacPDDZrkzfsT6MPlPnmO37qoSBp9Q30ac5zv0D43gbxU9Fpz+ed37VagaTPwayIjY31IbxkMx5xv7AYp91bQqEbGH0H0xHeslQkygTlnpqOHm9x9genN3xYhBiHBe2eAf6ZJAXe+IF7i/vjSeTEpzxSlI9Tf2lk25C4W8+5ulT+mHlu2BLp9cwAq4IHTW+wvnOMAMr9yP2/Vm2urqoKA4EPYJ4iPJ3vkBqDxGPrBnaQFKq/v+N/6jpGr6XHIkrsXE2XjpdYZfRcudiyVf88QAjVCfjEW2pXTy+7BFloIc5qP86MH3c3IP0oKyT7/xxjRlSp38vp7pKI3eUvLCvk9F6BunmTlXG/4rQdVP1/L/EYmFJTbWrgMZWLVAvnEt2OTJLCUsPMzmHPpwH1CfLFsMvkwuaD45M5fU40oO1fkR29hyceFkWQUL6Qph0lsT7LYhn8XtneTmwDuER7YkHBtOpoVljyR8Rg3MYx3HVW5nzTftbxJLIhWu3qPQb2g4aC6NlsqZLHss14/JjP3mFPWvAbOHV0ekBj+Vpts/yrjEQAFwEdaIeSLJ94g2uAXpZp2IV7W5aiuoz/o0aCgIbHCFZ9pmtt1ewNvBhqfioZiI3ZCmLKjyqzyRIve1bxG6xzUSV8NwtcKP8OVY1AOOsF2Fr2IHFKMMmvJfBzdIRtIHr0iVjy/rLN/6mZjHRJ2WZfzVCvIXbb1KVPtGqtPs8UmTZxeeohPeKJZeJ67rPxtUHomQ/tMic1RV+BGEwIAxiwmOYFq2yCZ6nRYa13IxzHMOch0V7shtOWIEydLbT9N/xUzQ5WC5AwjbNjK/Dm7b7IwY2dIt4AyP7mtqI41+E+ktF6LnoqZBTKOcVzadYTpSHw+yGXf8Ge4sDty99I="
    }
  }
}
