{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "regcred",
    "namespace": "rt"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "regcred",
        "namespace": "rt"
      },
      "type": "kubernetes.io/dockerconfigjson"
    },
    "encryptedData": {
      ".dockerconfigjson": "AgBNCgjNVsGoowSa9+jAVWVk8ncTzrUHoVS9DlplPCPCH5hu3lnM/P7cPVmC3HXHYwYQ0ZQIWVLE2ipRp1T46X6YqaXaQYnRv5CHBq76oOlJSruK5fHi8cl3pBzSetB+0FfkFcSmT922vS31lAhV5+rwgKf4o1I2It2fpmCNvLqNi8puwAVGufs6K65kiUYofA+2Z95loLWEOqaaGXsAb/mpyfIWZbXLtlGJAt3PtfaYzFvIHKc1zzXmQdY8La1m6CCrCUcWVgEOxGTePHNh4gl7ck4vFAaR6YUupDUa87H6+2vSEcJ13oN98aWhn0fGHrsSrGdpD4GUqctyn7b3SzvCAG4svmF8GDydNDeTx123xvIyiThVQncbh96p/KQG6p7dy+HGFubDwabjhPEpNqTR8fRCY4X+oxjSPCECBbjsO2oMf4df8Tos3Vq7MMMHQnAYZr/H+ts5czwSghUgJZzrQy6BL5FlmsW1lXSmAaOPlPagtZ4tWVkgm38r3Uv601DxMoKNNibNV6XEmIQeIc/IA6IDCfu92UPliig1gKI+qT8PtLHgFu0ngfxQKzlVtVx1X0uuq3kW8jHydpFdxLRcsy7DnAPwADiCHZcicN4y5JkbKWDHmOnd/B4T0mMtBrX4tHFve8bHApKfRw0Eetm66FqS0k5ZgrpY8KUVwoDRcUAoUfyGEdgmX3W7Ob7y5eQPaTN/ExFx0JQtdy1IPNiTS9CANrXPY0a4qIQSZET3YPUL6dooKQwbsr0AzMaSYDu9jbAPviHTbB2VDz6rqm4dcxyhRhFFiwhhv98S+x8FTgHhzR9gDV72OV/TSgO0VP9vA6qB8izQayB2y4r94zxkQuWhmhqsuJt9ptmtd6JI+UQ16F5pLjKXg789+wzzkl/Dflll4gc8HnYakVykCZMJiLFfsVpyBECnCy7Z+KhH51fKatALF9c="
    }
  }
}
