{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "postgres-secret",
    "namespace": "rt"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "postgres-secret",
        "namespace": "rt"
      }
    },
    "encryptedData": {
      "postgres-db": "AgARgRVblYjDNF01DSGm6bi+3ULLQfYpW6mWtV0CN3hBvv9uLiSpP5oenVhKB3fa1W3tDIU2fZ1koZEP8JN/De+5AXwWdoVEUkutvtvSBSPVSOrmxqhVECo7IWwx0vz4MZa+0XBxPQnar4zB+RvxG/9F01DEZVwD3WK63xI1idk/TBFTcrZHfj4akkGYFAq+b/bJqKaxe+zKZM7omk7nJsAEOvAXefDLqfYSHUj1uU+uyscXBEM0vsWZY/KQh4Tzy7/HVjupg3zAyFx0zwhUSnI0Ltycv3nMgm7dHUFXZZyE/+wHYUXPbFkWj/7v6l5nIUkHwSP61KpFaH3uaNZ9aAG09xd4J9CltCvkrEIVLgfA3nSfyyZL7PVLdnjRUnpsK6eSLXFbwafTW6PU8iRkoQk3QSY3y4dSqe3e4juw7FdT6aEJOCjt/ppc6hE1tSnQNAjAEJZfbEMxR6Wk0B/dWcnRFiCRV6cj5AHygEjsR7U9qMtW0c33bhGWvQqUSAqhKK/wKnf1utabp19GZlfbR4wyLdm42h/NWr/bSah1iPlii7u5GXv5vU24UyH8/LbEZLx6kmHLCRn+GCtOwR/XnrtCKVeEBF/mX7ayygkDNvRYMop0FwOhL5OcYq47rhgmhd6eDXfXUIt2OAB+6xomspgqMkkWIItBcsHUJLbS40OGFRGKR2IgtLnxCrA3olUUD2yAPcDMEbCv9Q==",
      "postgres-password": "AgByW+1UiN8QczQGVZ5FyH9cvY6+hDMTnP2ouZY9piUKiotHxT1f5aePMdKEc+KAzzxeEVoEE3AW2wmHPHyuqBq8BfzSpSKW1pgP2IcUcybO+m73p0LynIa/kMcXZUW/RDmKkY0sQKvyNgpOgPC3vMw64SjPUxcgJ91yckAyhxZZo2jaE9+57sOAjHlmALNA1p2dAB7pP44KogFQhI3QwXpI2ow+2oCQ6z+RXvsZs0K4uiojC24pgDtjqibAxNhCMKNhg6MDK/KYVucD/wzLW78PbNNT+UjWdVh9lxirop3ngI/DVR0wMJj8u7EZHjFs/vW4uIaiFrN54fHk+LRu5kKtYWMiHx3unkCEs7tnKM3NTF6NHcQTobjyqqVzyOhgbG5wIvVFKp5kDiUUlooGN51JwIWhW0j6EGGQsrUzMqwq6TW7/KvFTHSZQ2eGq3IBBEXY7C06nkQhGrSnFiolHdtqV3By/KGeaE0EADrUFLykqgLiVUJij+Y1SueeGIDA/d9M360MPH3YV72jHcc7Bb2WuOY35pQSWTz/Y7qhpMUq2ZcVChdnKozuJjqw+FKCn9IyE22VsRMvCDSIYF8DAibbBoBu1JKiD5WjSIcpf6IK3n1nVA+5AFkob64ZjpvFfUY4h1A1HDqX4OKucZSHWvufNfF0T13SwVwUgYcwZLU/eM0uM59NWQAlLnqG7SOcul8qhu7LTH6mGGABjc999zoXqMC6xAe3aA==",
      "postgres-user": "AgBocV7bFD6gUv/2f4vmRE30N73Jxh8IXcQHsXFgIauk4dZlnwBMR65DYggQjTruqTKN1I7Y9DzJkptlo83sZONf7uHVQr3tbuaNW+vA8YisokpPyFqXeB1R4k8rvOihMkkdSH2d0D+Zh8IEVS3mCBomgTzF6G/zYxlbI9MzFdswmou6gbTVvdbtuLdMJifHO9eiRov73nvIzMYlV5yMWFo8jyIuJ9dbNvH+Ls/ioJN24d2YsAAOrI3ajgii2Axex9aERv9jPyPOZ2upmR1TqX5WRo7J7PYMZ//Y8xLggLc9/pe9vGYwAOAoSR4PRCPCdJtf4sUPWD9U4Wcf02BxdD1EyBtGYXogGRTIjeQUJLsFlYXv/np0BBScsfDpXASa4lo1IjNQZRjEQR2fTuFNRttz7JFYY9P0CId6AE84BozeiBD/HIDk37dTVqCVDRFExgeATa88fdjFeQujB/TvFt/fCRY+smddSD/dBIPOd4nlmqkv3c5v0tUePyinMMhO+tqCSBAYWQvqCgE6sPP8dDqQcTN4WWs1UTRAn+2/roYtiNkSANLugJzYmW1JoiX+Ti3mjnIC3jVCoAvnzJLSVJutPv6eHcTxHhzJcAhrGBWip45B4Me8p+c/dVgfX5IqI7+Gt/D259WmDEIOeC5JWmqtTk5S/Dcjcj7nemxBhpQNUYuIzHwVHr60HXyKq5o8q3ViKWHPzPlRE61y"
    }
  }
}
