{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "postgres-secret",
    "namespace": "rt"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "postgres-secret",
        "namespace": "rt"
      }
    },
    "encryptedData": {
      "postgres-db": "AgA/arRzqo40lUjmEQMMeTGObIZuYFtWrv+S+CkdnWr+yEyqnFm48yYY1kNec5Tl22Pv7jiyq6nMquPncMddO1gjWhELZidGQovgKNfR4SgPcJjNRYV0gycEZmGW0/z9T3m/plCrKwr+nmySeSYcp4lIj7XZJr9cBk3lExB+ZNTAXY1NXud/gLa7JAfZvmv1f3JGCafo3GWVwN4/x0Ufg4ljh50UHSgYoqjeSLrxxme+I963ljG1VW6LuEcxvLumfcBj6oL6KnoLUFeEcUzVqPhjKDan6oxesD3ugCl5MzG/cU94FdLXFYO5EhtkfvwkW95YfntjgODLej5dGP07CjuFS8M8opwetsXqPYWlTgjD6UHYR6GEaxXLacdiA2bJ+IGTUJoEh4cT9mcxeK3OLWktShpO/31TY7fok7QjT24Gf1cL/6TPkqO/3nHst2GkGYBsv/UkZTDp2NiujbAyUgrzWI6NoXRi0FRiRT9AaMonkV6OnqiW1WESaFgRrBfowasCCZUtWtuzF5L04TiHW6z3P677k12ziReQho4sXf2nOo/fUjOphRjnaM8WPMoCSxdq8sUvaBCeD7O4Ooj3zXH5o6IzAeSWtrLSOiPpZqUTuq5PLqVP+5GJTMy2QYHBPbwoytI/ewz/slqAOAZRGceelq6sa89hSdOo7U1HPj2UXo+FA7XnrUwcoRwpObkdOWyLgfmePGwjnA==",
      "postgres-password": "AgA5X4hofqpBOXKKoht1ziS6BQedTHpaPyLu6howtqIxtOjgU92NNFyuntOflL5SZhjhY0CVAeOlfiFkxWYm9IscubbvJ9IV+fBeqRGsV96ryLD6xZgnjtXHY0Lm6MRPj6SMADiXDErf7ZyOS/HIVLowOXz1zTBHYs1Y+zu5mJ1NSMjp9xxw7QDU1V3kci2Yt13LfN3vVkom9+Hw/IG7AZ+iF8RevRIvOPxPhoMSeg1MZpm+4firxPljJT+h6kxIhCRGiCF8QGkmIx5+9wt8IYJaK/zgE8tBpK3R0kHCyOZiq7Ul5NBIwd0sG6h53kNWqAAKeZccfhNLxo1LZlXgAIw8uu0Q/E4MiBqeHltZIzTp4MiaYcoTwzeQhGPs/pYQg0xnfjEama4Zl2Kw2QQcFYQAG4e5bcQFwdmYvbDMrYE+JfH03+ZOiSGtYJH+adFRxeC4phK+mfTrzAVS9Ru/UfPp6YHLsGGLH1knY8yfbqMHrZIVQdmdYDw+GqI8bb+OIE/lXcKJluPWDpaVNbSxLqFY7oF/dxLdEQDGyF1S/83T6kDkJdrIBkap4n/Z3xqz9d7u7sBy8KdlwCHNG8RQntYRzcRlW6bW2+Wm4H1utMfoFPQ8YbKI5BpJt7VR7hKt44gf+5KNwElP6xkAneP/6ooXCNoEw8YbHTwDuLO/YFX4h5L2EbOVm2lJo2/BYuudkHvMtVt8itnX+9iezzgRDjHSLtvqhYdVzQ==",
      "postgres-user": "AgBKY2D1Ds1UupM9YMrJARedieVc9Lgq4wtKvjbfbdzmu5QGJxK5pbDVu/N4lMFhyXmmUOD+RSgpkFSTxTGiPmdicz6BRXCtlPH+U4TI2PJTphYVEae3c+EkoMEcxhp7xmSNYO551T0Xtdr/Qzi61TAqtNrTC999OZTJYGjB/n/GHDWNDo6ZP7P/hkdukgWh6pLKU7TtsCFVw9b6dAANnKXJkxCJNBrhtZWN7bhKYHc7E5kRY9QmJwI8dWjEnC0CjiXIvmczB3v/G5pPUtVeyq+zRxzTwa2Q8T/xcdKmiwnLEamgvkCzF/SDQib809oCY5NtHON+Phkhz+U6dOzQpN8xpzspnrZlrALykUuyGLAFJGMeF/mgLSiwJQHk5cAWurXGXHxtdyGOXkbHLOZEsb6pFSAyD3b26BG0RFTyTiA6MeFPPieDKFtP8FHhYe4i+F8lVbcmjZ6yn7amRL8i0oc7Oc9jibPTot7nERpxDsn/RfFifTN6831gXd/bbMXL2sEW3dUXRJA7It7uTvkeppguqGKPqhT/K8LyBhvpjcP31BsSPd3YLPwFNjFc8+vga/BbWEtZCwtYBW8GWxSKb9jSz2800y9Ibgf5foLKtXU1fDVputoQKvxzy8JMhaN05HFNQ0JEbb3SCrYCu96m9BpkW6Qr1oT6XXrUbmTSrKC75rtZ/M+cZpQFChGh4K6v6fy8ws1ZEOKjyGYp"
    }
  }
}
