apiVersion: v1
kind: Secret
metadata:
  name: gitea-secrets
  namespace: rt
type: Opaque
stringData:
  # stringData permet d'Ã©crire en clair, K8s l'encodera en base64 tout seul
  db_password: "monSuperMotDePasse"
  admin_user: "admin"