apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: forge-ingress
  namespace: rt
spec:
  ingressClassName: nginx
  rules:
  - host: forge.IP_LB_PLACEHOLDER.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-forge
            port:
              number: 80