apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
  namespace: rt
spec:
  ports:
    - name: jenkins
      port: 82
      protocol: TCP
      targetPort: 8080
  selector:
    app: jenkins-apps