---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: digitalocean
  namespace: kube-system
spec:
  encryptedData:
    access-token: AgBjyYXdHSODSGNQR7lallPuCgDMvhudNNEc680KGDXKMC9cxJIfQUpD6Pmb53HZswNm/Ia9pBYsoCxbYox2N9Px3vbyu/myz7zmfNy9tmL0aZuwdvsNfGYYZqNSfYG0e9iAe/YA4eI31TvKzS3SHNLN/zWEjz11np70enqBnDbwnUYhsJVMOPhGf5hjo915H/EQrDUFXs1OADsvORmy7JCkc+1+0ly+uD1/Ec0lt5JqK7qVPfTAA88IVlB/hxuskTcSqb5PvaP8bngP6CkNvg/r5K0grSK8Mbv5LSshwCkjQspa6hYx7XLbJcfUXB1xnqbUvn9SFUjLnC9XuqZbFQGKQDYQf4hR4dElYuNKITEkq3ivMgKNR0/SGCkLb+YElT4a4WTZvMZB8GKYGCawk1EcdHNtzPR94nIMJfEvtCho7wBDobFbTju5fBg9DW9PNRh5zj3EwZtvZufDJ7jEOzRsBsqY76UZQFAT1xBQzSI5lu3F5qxzSiF8hbOOM5ttO+atuaGKUKyYAvWzaJKY5t8z2F2xdLydcjYNu0LEupb5hSg7akBbXaRMtklmDEgUWDFyqPjJyrxU9Dgshz696tFXo00tPjtUpm/o95Cwgrsb67qh9OlJtzc0hL9hkAj2k9T1XOOR/v8EsupoYLeiSnANkpJfGfEGhVhaVcP5aDVeQDRF9trnekysaTE00hXGX5t8poU5N5ZPuxU1/ZVMhizMX7FCDQxzKcByG9kPo2vv9x80BQ2nliziCjj4CznpqN/j1Dd2AnsZpXQinwa5Yv0W6m3+W/WTbw==
  template:
    metadata:
      name: digitalocean
      namespace: kube-system
