---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: digitalocean
  namespace: kube-system
spec:
  encryptedData:
    access-token: AgAOi3/qQFLn5lIUiIXkkNUX7/4wdpms2BOD3kTCtBnnbDiJKXwnTbbi12F2yiD17DB7o5qBGS2mN7eI8mdya82jvFIKk13G2m+bEFDtOdIn23jrlJEJmHQTbodKh5C30qyuknfiSW7/Y5zH8grEq1SFw3mHlPVjCswPXylnHvrJqSWp1La9oBktA4QBlG9ASSWOO2VWgw/mU954cToFCv5H+g4yy2hiiWceey8K7pfV2o6anbP57E0qNFWafdsVKYwSq73J66M1ieZkMRbJZgV32zA+rYGoq4Pq9vXHSdo+HaQQxNwXtS+X6QSa4w0bp8TSs6F0Z2PWkAQF+rNK/sFiGo6Ai97eywLFa1JnFmVSpKa9K7Z5DJttNRJnAR/DQGR6rUVUpMLW9GBkFBBoZS3R04DLi9yjgDtG4P2dz2cOCWgJRbUSiGYn5NKhALPma1fmgHZVr/GazQTTcK9dmOOQUmlEiNqr0/rWHF9e+osw6Yh2M71T/p0W6QtuJPS7UCs9xyH3LvuHIGGIY7sZSO5Rj9CRdQc03te5NJPfBnmh5+LG/+ghRhnTmafxwQ71mQ7YoJH23KFZZhMMqTRzStwD69QiJmAwESAoacWVAZqwMyVW7rroHiiF3GnbtxdmZfHb6CUchXxFX6UIktQLANkqKGVYftWGMaLjJ0Bay06xNsrUJ5JyZF+ejJ7IvqfvbnNRIsISbk/0ug9gz6QJk4JfWC8pobJ+7pW3KwZGranAz3fV9x3R5Oh5bxz/PGSy4VONOkxpPg4g/QINb779jA3u1n8UfLuR/Q==
  template:
    metadata:
      name: digitalocean
      namespace: kube-system
