---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: digitalocean
  namespace: kube-system
spec:
  encryptedData:
    access-token: AgBw6Yz+v6Dto6oX96PYvcSVyljaUkNvh0s6Y8W21zUKGmzjDMoOTOXxdR+d0G9TpSKk7qzExVBGte5avEFqljjMqVx1Wc8087kUdPi71EnRzjwlHuHNBIvYg7cXb+0Jf33AGJL//mRHrsfS5FtB1qqT4oQKwuCSDmWvgql0Wk4uxSEWn16WPs4I/ZMrZd1PpaYTIbKHYu2lfc2ryi9SaGhuIoMGL0IlVdwEvpb3ewOMYyh3yl2hTtz9jOsnVbohlpFHnDt3cp/xUI4ZnAAvgZZ9jMfcRSQGyNXhAuomvQRJ4iz/Q8MDgLIpy4MGqyldgxkNEo1mbB/Gaz79a6kseBi/SvfwJJd6cnV47VootzY2pgUuFXJCiIHINXT2M49yauhKw1CT5k9/NbT3k/mtr1ogytaDjC96GwXyz3Yxa47jpQy/TTvgW77dA843Aisd3fsTH7fFcMxgajpL3POySfJ5XhQTS2wLVGEPYFz/YF5EUaYD9lgyKU17eIEcvJfJ8AOTyFLisUtCYvhk0pMy4zlBs4l1wpXAMMG46vC68k7XFCD6dBth3No7pIong0Pob4Y0qPZgEURDwrn5DfsLio9irw/89FZmOk0ZmTL5GWYsgb5hniMf43M0aGI9wiWBbInelsrVBQHE3CMfjEzF9WaD69w9JQjjTqxY0nJTjKzti07ucF5nZZiNWf8uX+3qLB190aDscdgJawhMfvWuffDfe90Zr5j8ScBcClaOMciL29ji7DGxcJ8MWswiL0eJL9SQgvD9BwUyrRe+WaUVfao1cjzb6xVFAw==
  template:
    metadata:
      name: digitalocean
      namespace: kube-system
