---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: digitalocean
  namespace: kube-system
spec:
  encryptedData:
    access-token: AgCnXZ8ISWeGlnPNmfuYzItufVHFBOSkiTmrWkNoR0GuatRHWwguY+bYSmvl5zycEsS/Xk1rklbJqABP6zJtRDF48Bbn0MlRnHjyqTqst/x6KHnskv3O3dAilet/x16ZUfkuk81OGHeCjH0MN2evsZhVXQIVOBRBeswmjgsTs2zDx/Oe570vKP/iEm43QOe4dbEXYz4C1VCoNbpJA5BkzynrIMgy2FXfcxiB3LjbrbGyL9a7Nxop9IjQOnwNRkMRUuTzilpgAqHGc/yfJNJnVkvT4bvTLAPPTm4qtbY/9mufojovj0gAOkG9Wij1ZM+Qp492zry4FBClJ6V+KD/KNOgOvPLf9PKQgk5wpwtNNQHyx3Kj+aCurgmdFYSAWcCVQIvVzAa3WHnA7QbfkxxJ1yT2tdyg57gubcGE2sJXX4fgujGNSedaivV2afrx3RiYuH0oIhBsR6EhLtOhfXVrC1iJIc5rEYNAxzB+Iia4o+UcfU0l+K0mPm2Ho8Cae5g5EP8uzRyqwjphbo5Gj4dw181cZARuY+Kix4IpI2vvsOIcvR/L6YmxEWwdXCHSq5LjSAcgBFYsb8/PbEWVlBXaAGN/I8J62Nk6DEXfgFMBcp1V6CvTJZZxLa5FODuf2xZFUeY4ZVRDAyVVo5m7JLADAh7QToLGS+u8SNqeYNrTRNAIEvWYpoHpCb9DHF3Edll5tvehh4nJf0OoEW1wxFwJNqj1CUxEqTdb0wVKYspPQqJsE45l1P3bgIvnXPuhaV4Vtu2E+EAeShShOx94OBI9sFYTJiVSY2hfNw==
  template:
    metadata:
      name: digitalocean
      namespace: kube-system
